srmsystem/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    # change password urls
    #path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    #path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # reset password urls
    #path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    #path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    #register
    path('register/', views.register, name='register'),
    #edit
    #path('edit/', views.edit, name='edit'),
    #users list
    #path('users/', views.user_list, name='user_list'),
    #user details
    #path('users/<username>/', views.user_detail, name='user_detail'),
]

srmsystem/srmsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('website.urls')),
]

srmsystem/website/urls.py
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static


urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('series/', views.series_list, name='series'),
    path('races/', views.races_list, name='races'),
    path('drivers/', views.drivers_list, name='drivers'),
    path('cars/', views.cars_list, name='cars'),
    path('tracks/', views.tracks_list, name='tracks'),
    path('rules/', views.rules_list, name='rules'),
    path('rules/<int:id>', views.rules_details, name='rules_details'),
    path('series/<int:id>', views.series_details, name='series_details'),
    path('race/<int:id>', views.race_details, name='race_details'),
    path('challenge/<int:id>', views.challenge_details, name='challenge_details'),
    path('cars/<int:id>', views.car_details, name='car_details'),
    path('track/<int:id>', views.track_details, name='track_details')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

srmsystem/account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User, AbstractUser
from website.models import *

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True, default='https://i.ibb.co/KGZKQFx/av.jpg')
    bio = models.TextField(verbose_name="Bio", max_length="200", null=True, blank=True)
    nationality = models.TextField(verbose_name="Nationality", choices=helpers.GetCountiesDoubleTuple(), null=True, blank=True)
    races = models.ManyToManyField(Race, related_name="drivers")
    series = models.ManyToManyField(Series, related_name="drivers")

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name + ", " + self.user.username

def get_name(self):
    return self.first_name + " " + self.last_name

User.add_to_class("__str__", get_name)
        

srmsystem/website/views.py
from django.shortcuts import render, get_object_or_404
from .models import Race, Challenge, Post, Series, Car, Track, Rules, QualificationsResults, RaceResults
from datetime import datetime
from django.db.models import Count
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from website.lib import xmlparser, helpers
from django.utils import timezone

# Create your views here.
def homepage(request):
    today = timezone.now()
    next_races = Race.objects.order_by('race_date').filter(race_date__gte=today)[:3]
    latest_races = Race.objects.order_by('-race_date').filter(race_date__lt=today)[:3]
    challenges = Challenge.objects.all().filter(date_start__lte=today).filter(date_end__gte=today)
    posts = Post.objects.order_by('-publish')[:8]
    
    #user_data
    user_race_count = 0

    if request.user.is_authenticated:
        user_race_count = request.user.profile.races.filter(race_date__lt=today).count()

    return render(request,
                  'website/homepage.html',
                  {'next_races':next_races,
                   'latest_races':latest_races,
                   'challenges': challenges,
                   'user_race_count':user_race_count,
                   'posts':posts})

def series_list(request):
    today = datetime.today()
    current_series = Series.objects.all().order_by('-date_start').filter(date_end__gte=today).filter(isSpecialEvent=False)
    past_series=Series.objects.all().order_by('-date_start').filter(date_end__lt=today).filter(isSpecialEvent=False)


    return render(request,
                  'website/series_list.html',
                  {'current_series':current_series,
                  'past_series': past_series})

def races_list(request):
    today = timezone.now()
    next_races = Race.objects.all().order_by('race_date').filter(race_date__gte=today)
    latest_races = Race.objects.all().order_by('-race_date').filter(race_date__lt=today)

    return render(request,
                'website/races_list.html',
                {
                    'next_races':next_races,
                    'latest_races':latest_races
                })

def drivers_list(request):
    drivers_all = User.objects.all().order_by('date_joined')
    paginator = Paginator(drivers_all, 40)
    page = request.GET.get('page', 1)
    


    try:
        drivers = paginator.page(page)
    except PageNotAnInteger:
        drivers = paginator.page(1)
    except EmptyPage:
        drivers = paginator.page(paginator.num_pages)

    return render(request,'website/drivers_list.html',{
            'drivers':drivers
        })

def cars_list(request):
    cars_all = Car.objects.all()

    paginator = Paginator(cars_all, 30)
    page = request.GET.get('page', 1)
    


    try:
        cars = paginator.page(page)
    except PageNotAnInteger:
        cars = paginator.page(1)
    except EmptyPage:
        cars = paginator.page(paginator.num_pages)

    return render(request,'website/cars_list.html',{
            'cars':cars
        })

def tracks_list(request):
    tracks_all = Track.objects.all()

    paginator = Paginator(tracks_all, 30)
    page = request.GET.get('page', 1)
    


    try:
        tracks = paginator.page(page)
    except PageNotAnInteger:
        tracks = paginator.page(1)
    except EmptyPage:
        tracks = paginator.page(paginator.num_pages)

    return render(request,'website/tracks_list.html',{
            'tracks':tracks
        })

def rules_list(request):
    rules_all = Rules.objects.all().order_by('id').filter(isRulesDescription=False)
    rules_description = Rules.objects.all().order_by('id').filter(isRulesDescription=True)

    for rules in rules_all:
        print(rules.title)

    return render(request,'website/rules_list.html',{
            'rules_all':rules_all,
            'rules_description':rules_description
        })

def rules_details(request, id):
    rules = get_object_or_404(Rules, id=id)
    return render(request,
        'website/rules_details.html',
        {'rules': rules})

def car_details(request, id):
    car = get_object_or_404(Car, id=id)
    return render(request,
        'website/car_details.html',
        {'car': car})

def track_details(request, id):
    track = get_object_or_404(Track, id=id)
    return render(request,
        'website/track_details.html',
        {'track': track})

def series_details(request, id):
    series = get_object_or_404(Series, id=id)
    cars = series.cars.all()
    races = series.races.all()
    rules = series.rules.all()
    entries = series.drivers.all()
    standings = get_standings(series)
    ballast = get_ballast(series, standings)

    if request.POST:
        if series.drivers.filter(user=request.user).exists():
            series.drivers.remove(request.user.profile)
            series.save()
        else:
            series.drivers.add(request.user.profile)
            series.save()

    return render(request,
        'website/series_overview.html',
        {'series': series,
         'cars': cars,
         'races': races,
         'rules': rules,
         'entries': entries,
         'standings': standings,
         'ballast': ballast
        })

def get_standings(series):
    races = Race.objects.all().filter(series=series).filter(series_race=True).order_by('race_date')
    drivers = []

    for race in races:
        try:
            xmlfile = RaceResults.objects.get(race=race).file
        except:
            continue
        race_result = xmlparser.parse_race_results(xmlfile)
        for driver in race_result.driversRaceResults:
            if (len(drivers) == 0):
                y = DriverStandings()
                y.name = driver.name
                y.points = helpers.get_race_points(driver, race, race_result)
                drivers.append(y)
                continue
            
            if (next((x for x in drivers if x.name == driver.name), None)):
                for x in drivers:
                    if x.name == driver.name:
                        race_points = helpers.get_race_points(driver, race, race_result)
                        x.points += race_points
            else:
                y = DriverStandings()
                y.name = driver.name
                y.points = helpers.get_race_points(driver, race, race_result)
                drivers.append(y)

    return drivers

def get_ballast(series, standings):
    races = Race.objects.all().filter(series=series).filter(series_race=True).order_by('race_date')
    races_with_results = []
    for race in races:
        try:
            xmlfile = RaceResults.objects.get(race=race).file
            races_with_results.append(race)
        except:
            continue
    last_races = races_with_results[:2]
    drivers = []
    for race in races:
        try:
            xmlfile = RaceResults.objects.get(race=race).file
        except:
            continue
        race_result = xmlparser.parse_race_results(xmlfile)
        for driver in race_result.driversRaceResults:
            if driver.position < 4:
                if (len(drivers) == 0):
                    y = DriverBallast()
                    y.name = driver.name
                    if driver.position == 1:
                        y.ballast = 15
                    elif driver.position == 2:
                        y.ballast = 10
                    elif driver.position == 3:
                        y.ballast = 5
                        drivers.append(y)
                if (next((x for x in drivers if x.name == driver.name), None)):
                    for x in drivers:
                        if x.name == driver.name:
                            if driver.position == 1:
                                x.ballast += 15
                            elif driver.position == 2:
                                x.ballast += 10
                            elif driver.position == 3:
                                x.ballast += 5
                else:
                    y = DriverBallast()
                    y.name = driver.name
                    if driver.position == 1:
                        y.ballast = 15
                    elif driver.position == 2:
                        y.ballast = 10
                    elif driver.position == 3:
                        y.ballast = 5
                    drivers.append(y)

    standings_sorted = sorted(standings, key=lambda x: x.points, reverse=True)
    i = 1
    for driver in standings_sorted:
        if i == 1:
            if (len(drivers) == 0):
                y = DriverBallast()
                y.name = driver.name
                y.ballast = 15
            for x in drivers:
                if x.name == driver.name:
                    x.ballast += 15
            else:
                y = DriverBallast()
                y.name = driver.name
                y.ballast = 15
        if i == 2:
            if (len(drivers) == 0):
                y = DriverBallast()
                y.name = driver.name
                y.ballast = 10
            for x in drivers:
                if x.name == driver.name:
                    x.ballast += 10
            else:
                y = DriverBallast()
                y.name = driver.name
                y.ballast = 10
        if i == 3: 
            if (len(drivers) == 0):
                y = DriverBallast()
                y.name = driver.name
                y.ballast = 5
            for x in drivers:
                if x.name == driver.name:
                    x.ballast += 5
            else:
                y = DriverBallast()
                y.name = driver.name
                y.ballast = 5
            break
        i += 1

    return drivers


class DriverStandings():
   points = 0
   name = ""

class DriverBallast():
    ballast = 0
    name = ""


def race_details(request, id):
    race_object = get_object_or_404(Race, id=id)
    entries = race_object.drivers.all()
    is_future = False

srmsystem/website/templates/website/car_details.html
{% extends "base.html" %} {% load static %} {% block title %}{{ car }}{% endblock %} {% block content %}
<div class="flex-container padding-30 flex-center">
    <div class="mod-container">
        <div class="section-title border-bottom">
            <i class="material-icons">
                directions_car
                </i> Car Details
        </div>
        <div class="section mod-section">
            <div class="item-normal mod-item">
                <div class="item-picture" style="background-image: url({{ MEDIA_URL }}{{ car.mod.picture }});"></div>
            </div>
        </div>
        <div class="section mod-section mod-info-section">
            <div class="mod-table">
                <div class="entry-item">
                    <div class="label">Car</div>
                    <div class="value">{{ car }}</div>
                </div>
                <div class="entry-item">
                    <div class="label">Car class</div>
                    <div class="value">{{ car.carclass }}</div>
                </div>
                <div class="entry-item">
                    <div class="label">Mod name</div>
                    <div class="value">{{ car.mod.name }}</div>
                </div>
                <div class="entry-item">
                    <div class="label"> &nbsp; </div>
                    <div class="value"><a class="text-link" href="{{ car.mod.mod_url }}"><b>Download</b></a></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

srmsystem/website/templates/website/cars_list.html
{% extends "base.html" %} {% load static %} {% block title %}Cars{% endblock %} {% block content %}

<div class="flex-container padding-30">
    
    <div class="section time-trials">
        <div class="section-title">
            <i class="material-icons">
                directions_car
            </i>Cars
        </div>
    
        <div class="grid-container races-homepage">
            {% for car in cars %}
            <a href="{{ car.get_absolute_url }}"><div class="item-normal">
                <div class="item-picture" style="background-image: url({{ MEDIA_URL }}{{ car.mod.picture }});"></div>
                <div class="item-title">{{ car.manufacturer }} {{ car.model_name }}</div>
                <div class="item-data">{{ car.carclass }}</div>
            </div></a>
            {% endfor %}
        </div>
        
        {% if cars.has_other_pages %}
        <div class="pagination-container">
            <ul class="pagination">
                {% if cars.has_previous %}
                <li><a href="?page={{ cars.previous_page_number }}"><i class="material-icons">
                    chevron_left
                    </i></a></li>
                {% else %}
                <li class="disabled"><span><i class="material-icons">
                    chevron_left
                    </i></span></li>
                {% endif %} {% for i in cars.paginator.page_range %} {% if cars.number == i %}
                <li class="active"><span>{{ i }}</span>
                </li>
                {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %} {% endfor %} {% if cars.has_next %}
                <li><a href="?page={{ cars.next_page_number }}"><i class="material-icons">
                    chevron_right
                    </i></a></li>
                {% else %}
                <li class="disabled"><span><i class="material-icons">
                    chevron_right
                    </i></span></li>
                {% endif %}
            </ul>
        </div>
        {% endif %}
    </div>
</div>

    {% endblock %}

srmsystem/website/templates/website/drivers_list.html
{% extends "base.html" %} {% load static %} {% block title %}Drivers{% endblock %} {% block content %}

<div class="row">
                <div class="drivers-list">
                    
        <div class="section-header item-list-header">
            <i class="material-icons">
                supervised_user_circle
                </i>SimRacingMania Drivers
        </div>
                    {% for driver in drivers %}
                        <a href="#">
                            <div class="driver-list-item">
                                <div class="driver-list-avatar" style="background-image: url({{ MEDIA_URL }}{{ driver.profile.photo }}); background-size: cover; background-position: center;"></div>
                                <div class="driver-list-details">
                                    <h1>{{ driver.first_name }} {{ driver.last_name }}</h1>
                                    <h2>{{ driver.profile.get_nationality_display }}</h2>
                                    <p>Joined {{ driver.date_joined|date:"d F Y" }}</p>
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                </div>




                {% if drivers.has_other_pages %}
                <ul class="pagination">
                    {% if drivers.has_previous %}
                    <li><a href="?page={{ drivers.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                    {% endif %} {% for i in drivers.paginator.page_range %} {% if drivers.number == i %}
                    <li class="active"><span>{{ i }}</span>
                    </li>
                    {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %} {% endfor %} {% if drivers.has_next %}
                    <li><a href="?page={{ drivers.next_page_number }}">&raquo;</a></li>
                    {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>

        </div>
    </div>

    {% endblock %}

srmsystem/website/templates/website/homepage.html
{% extends "base.html" %} {% load static %} {% block title %}Homepage{% endblock %} {% block content %}
<div class="flex-container padding-30">
    <div class="section next-races">
        <div class="section-title">
            <i class="material-icons">
                skip_next
                </i> Next races
        </div>

        <div class="grid-container races-homepage">
        {% for race in next_races %}
        {% include "parts/normal-race.html" %}
        {% endfor %}
        </div>
    </div>
    <div class="section last-races">
        <div class="section-title">
            <i class="material-icons">
                history
                </i> Latest races
        </div>
        
        <div class="grid-container races-homepage">
            {% for race in latest_races %}
                {% include "parts/normal-race.html" %}
            {% endfor %}
        </div>
    </div>
    
    <div class="post-section">
        <div class="section-title">
            <i class="material-icons">
                rss_feed
                </i> Latest posts
        </div>
        
        <div id="post-feed" class="post-feed">
            <div class="scroll-button-left" id="scroll-button-left">
                <i class="material-icons">
                arrow_left
                </i>
            </div>
            <div class="scroll-button-right" id="scroll-button-right">
                <i class="material-icons">
                arrow_right
                </i>
            </div>
            {% for post in posts %}
            <div class="post">
                <div class="post-header">
                    <div class="category">
                        {{ post.category }}
                    </div>
                    <div class="date">
                        {{ post.created|date:'d F Y' }}
                    </div>
                </div>
                <div class="post-content">
                    <div class="text">
                        {{ post.body|truncatechars:200 }}
                    </div>
                    <div class="post-thumbnail" style="background-image: url({{ MEDIA_URL }}{{ post.picture }});"></div>
                </div>
                <div class="post-footer">
                </div>
            </div>
            {% endfor %}
            
        </div>
    </div>
    <div class="section time-trials">
        <div class="section-title">
            <i class="material-icons">
                timer
                </i> Time-Trial Competitions
        </div>

        <div class="grid-container races-homepage">
        {% for challenge in challenges %}
            <a href="{{ challenge.get_absolute_url }}"><div class="item-normal">
                <div class="item-picture" style="background-image: url({{ MEDIA_URL }}{{ challenge.picture }});"></div>
                <div class="item-title">{{ challenge.name }} - {{ challenge.track.name }}</div>
                <div class="item-data">Start: {{ challenge.date_start|date:'d F Y' }}</div>
                <div class="item-data">End: {{ challenge.date_end|date:'d F Y' }}</div>
            </div></a>
        {% endfor %}
        </div>
    </div>
    <div class="section">
        <div class="section-title">
            <i class="material-icons">
                thumb_up_alt
                </i> Partners
        </div>
    </div>
</div>

{% endblock %}

srmsystem/website/templates/website/races_list.html
{% extends "base.html" %} {% load static %} {% block title %}Races{% endblock %} {% block content %}
<div class="flex-container padding-30">
    <div class="section next-races">
        <div class="section-title">
            <i class="material-icons">
                skip_next
                </i> Next races
        </div>

        <div class="grid-container races-homepage">
        {% for race in next_races %}
            {% include "parts/normal-race.html" %}
        {% endfor %}
        </div>
    </div>
    <div class="section last-races">
        <div class="section-title">
            <i class="material-icons">
                history
                </i> Latest races
        </div>
        
        <div class="grid-container races-homepage">
            {% for race in latest_races %}
                {% include "parts/normal-race.html" %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

srmsystem/website/templates/website/rules_details.html
{% extends "base.html" %} {% load website_tags %} {% load static %} {% block title %}Rules{% endblock %} {% block content %}

<div class="flex-container flex-center padding-30">
    <div class="rules-container">
        <div class="section-title border-bottom">
            <i class="material-icons">
                format_quote
                </i> {{ rules.title }}
        </div>
        <img src="{% static 'img/logo.png' %}"/>
        {{ rules.body|markdown }}
    </div>
</div>

{% endblock %}

srmsystem/website/templates/website/rules_list.html
{% extends "base.html" %} {% load website_tags %} {% load static %} {% block title %}Rules{% endblock %} {% block content %}

<div class="flex-container flex-center padding-30">
    <div class="rules-container">
        <div class="section-title border-bottom">
            <i class="material-icons">
                format_quote
                </i> SimRacingMania Rules
        </div>
        <img src="{% static 'img/logo.png' %}"/>
        {% for desc in rules_description %}
            {{ desc.body|markdown }}
        {% endfor %}
        <p class="table-of-content">Table of content:</p>
        <ul>
            {% for rules in rules_all %}
            {% if rules.series %}
            {% else %}
            <li>
                <a href="{{ rules.get_absolute_url }}">{{ rules.title }}</a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

srmsystem/website/templates/website/series_entries.html
<div class="flex-container flex-center overview-background">
    {% include "overview-header.html" %}    
    
    <div class="overview-menu">
        <ul>
            <a href="#"><li>Series Overview</li></a>
            <a href="#"><li>Standings</li></a>
            <a href="#"><li class="active">Entries</li></a>
        </ul>
    </div>

    <div class="overview-container padding-30">
        
    </div>
</div>

srmsystem/website/templates/website/series_list.html
{% extends "base.html" %} {% load static %} {% block title %}Series{% endblock %} {% block content %}

<div class="flex-container flex-center padding-30">
    <div class="content-list">
        <div class="section-title border-bottom">
            <i class="material-icons">
                view_list
            </i> Current Series
        </div>
        {% for series in current_series %}
            <a href="{{ series.get_absolute_url }}">
                <div class="list-item">
                    <div class="thumbnail" style="background-image: url({{ MEDIA_URL }}{{ series.series_picture }});"></div>
                    <div class="details">
                        <h1>{{ series.name }}</h1>
                        <h3>{{ series.races.count }} Races </h3>
                        <h2>Cars: 
                            {% for car in series.cars.all %}
                                {{ car }}, 
                            {% endfor %}<br/>
                            Tracks: 
                            {% for race in series.races.all %}
                                {{ race.track }}, 
                            {% endfor %}
                        </h2>
                    </div>
                </div>
            </a>
        {% endfor %}
        {% if past_series %}
        <div class="section-title border-bottom">
            <i class="material-icons">
                view_list
            </i> Past Series
        </div>
        {% for series in past_series %}
            <a href="{{ series.get_absolute_url }}">
                <div class="list-item">
                    <div class="thumbnail" style="background-image: url({{ MEDIA_URL }}{{ series.series_picture }});"></div>
                    <div class="details">
                        <h1>{{ series.name }}</h1>
                        <h3>{{ series.races.count }} Races </h3>
                        <h2>Cars: 
                            {% for car in series.cars.all %}
                                {{ car }}, 
                            {% endfor %}<br/>
                            Tracks: 
                            {% for race in series.races.all %}
                                {{ race.track }}, 
                            {% endfor %}
                        </h2>
                    </div>
                </div>
            </a>
        {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock %}

srmsystem/website/templates/website/track_details.html
{% extends "base.html" %} {% load static %} {% block title %}{{ track }}{% endblock %} {% block content %}
<div class="flex-container padding-30 flex-center">
    <div class="mod-container">
        <div class="section-title border-bottom">
            <i class="material-icons">
                directions_car
                </i> Track Details
        </div>
        <div class="section mod-section">
            <div class="item-normal mod-item">
                <div class="item-picture" style="background-image: url({{ MEDIA_URL }}{{ track.track_picture }});"></div>
            </div>
        </div>
        <div class="section mod-section mod-info-section">
            <div class="mod-table">
                <div class="entry-item">
                    <div class="label">Track</div>
                    <div class="value">{{ track }}</div>
                </div>
                <div class="entry-item">
                    <div class="label">Track Type</div>
                    <div class="value">{{ track.type }}</div>
                </div>
                <div class="entry-item">
                    <div class="label">Length (km)</div>
                    <div class="value">{{ track.length }}</div>
                </div>
                <div class="entry-item">
                    <div class="label"> &nbsp; </div>
                    <div class="value"><a class="text-link" href="{{ MEDIA_URL }}{{ track.track_map }}">Track Map</a></div>
                </div>
                <div class="entry-item">
                    <div class="label"> &nbsp; </div>
                    <div class="value"><a class="text-link" href="{{ track.mod.mod_url }}"><b>Download</b></a></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}